packages:
  secrets: !include secrets_substitutions.yaml
  base: !include devices/gosund-sw5/gosund-sw5.yaml

esphome:
  name_add_mac_suffix: true

dashboard_import:
  package_import_url: github://broccoliboy/esphome-config/devices/${name}/${name}-import.yaml@main
  import_full_config: true
