# Example config file for a Gosund SW5 node using remote git package to
# import all base and device-specific configs. The only required inputs
# are `device_name` and `device_friendly_name` as shown in the substitutions
# block. `device-name` must be unique for all nodes in a network.

substitutions:
  device_name: gosund-sw5-example
  device_friendly_name: "Gosund SW5"

  # Define secret substitutions here (remote packages can't use !secrets
  # so we use substitutions to pass in their values)
  # Alternatively, include a common secrets substitutions package as shown below
  # to avoid devining all secrets in every node's yaml file
  # wifi_ssid: !secret wifi_ssid
  # wifi_password: !secret wifi_password
  # wifi_ssid_fallback: !secret wifi_ssid_fallback
  # wifi_password_fallback: !secret wifi_password_fallback
  # api_key: !secret api_key
  # ota_password: !secret ota_password

packages:
  secrets: !include secrets_substitutions.yaml
  base:
    url: https://github.com/broccoliboy/esphome-config
    file: "devices/gosund-sw5.yaml"
    refresh: 1d
