substitutions:
  device_name: gosund-sw5-example-remote
  device_friendly_name: "Gosund SW5 Example"

packages:
  secrets: !include secrets_substitutions.yaml
  base: github://broccoliboy/esphome-config/devices/gosund-sw2.yaml@main
