substitutions:
  # Replace name with yaml file base name after adopting
  name: ustellar-50w-<MAC_SUFFIX>

  # Friendly name can be anything or leave blank for default
  friendly_name: 

  # Make sure the following secrets are defined in your global secrets.yaml file
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_fallback: !secret wifi_ssid_fallback
  wifi_password_fallback: !secret wifi_password_fallback
  ota_password: !secret ota_password
  api_key: !secret api_key
  web_username: !secret web_username
  web_password: !secret web_password

api:
  encryption:
    key: ${api_key}

packages:
  broccoliboy.gosund-sw5:
    url: https://github.com/broccoliboy/esphome-config
    ref: main
    file: devices/ustellar-50w/ustellar-50w.yaml
    refresh: 0s
