substitutions:
  log_level: none
  log_baud_rate: '115200'
  flash_write_interval: 10min

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

dashboard_import:
  package_import_url: github://broccoliboy/esphome-config/devices/${name}-template.yaml@main
  import_full_config: false

preferences:
  flash_write_interval: ${flash_write_interval}

packages:
  wifi: !include wifi.yaml
  api: !include api.yaml
  ota: !include ota.yaml
  day_night: !include day_night.yaml
  status: !include status.yaml       
  restart: !include restart.yaml
  version: !include version.yaml
  time: !include time.yaml
  logger: !include logger.yaml
