substitutions:
  # Replace name with yaml file base name after adopting
  name: cloudfree-p2-<MAC_SUFFIX>

  # Friendly name can be anything or leave blank for default
  friendly_name: 

  # Make sure the following secrets are defined in your global secrets.yaml file
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_fallback: !secret wifi_ssid_fallback
  wifi_password_fallback: !secret wifi_password_fallback
  ota_password: !secret ota_password
  api_key: !secret api_key
  web_username: !secret web_username
  web_password: !secret web_password
  latitude: !secret latitude
  longitude: !secret longitude

api:
  encryption:
    key: ${api_key}

packages:
  broccoliboy.cloudfree-p2:
    url: https://github.com/broccoliboy/esphome-config
    ref: main
    file: devices/cloudfree-p2/cloudfree-p2.yaml
    refresh: 0s
