# substitutions:
#   # name: "gosund-sw5"
#   friendly_name: "Gosund SW5"

# packages:
#   base: !include gosund-sw5.yaml
  
# # esphome:
# #   name_add_mac_suffix: true

# dashboard_import:
#   package_import_url: github://broccoliboy/esphome-config/devices/gosund-sw5-generic.yaml@main
#   import_full_config: true

# Delete everything above this line and uncomment the following

substitutions:
  friendly_name: "Gosund SW5"
  # Define these in secrets.yaml
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_fallback: !secret wifi_ssid_fallback
  wifi_password_fallback: !secret wifi_password_fallback
  api_key: !secret api_key
  ota_password: !secret ota_password
packages:
  base:
    url: https://github.com/broccoliboy/esphome-config
    file: "devices/gosund-sw5.yaml"
    refresh: 1d
