substitutions:
  name: "gosund-sw5"
  friendly_name: "Gosund SW5"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_fallback: !secret wifi_ssid_fallback
  wifi_password_fallback: !secret wifi_password_fallback
  api_key: !secret api_key
  ota_password: !secret ota_password

packages:
  base: !include gosund-sw5.yaml
