substitutions:
  name: "gosund-sw5"
  friendly_name: "Gosund SW5"
  wifi_ssid: ${wifi_ssid}
  wifi_password: ${wifi_password}
  wifi_ssid_fallback: ${wifi_ssid_fallback}
  wifi_password_fallback: ${wifi_password_fallback}
  api_key: ${api_key}
  ota_password: ${ota_password}

packages:
  base: !include gosund-sw5.yaml
