substitutions:
  name: "gosund-sw5"
  friendly_name: "Gosund SW5"

esphome:
  project:
    name: broccoliboy.gosund-sw5
    version: "1.0"

packages:
  hardware: !include ../hardware/esp01_1m.yaml
  base: !include ../components/base.yaml

status_led:
  pin:
    number: GPIO16
    inverted: true

output:
- platform: gpio
  id: relay0
  pin: GPIO14
- platform: gpio
  id: led0
  pin: GPIO2

switch:
- platform: output
  name: "Relay"
  id: switch0
  output: relay0
  on_turn_on:
    - output.turn_on: led0
  on_turn_off:
    - output.turn_off: led0

binary_sensor:
  - platform: gpio
    id: button1
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - switch.toggle: switch0
