substitutions:
  # Copy yaml filename with MAC suffix after adopting
  name: 

  # Friendly name can be anything or nothing
  friendly_name: 

  # Make sure the following secrets are defined in your global secrets.yaml file
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_fallback: !secret wifi_ssid_fallback
  wifi_password_fallback: !secret wifi_password_fallback
  api_key: !secret api_key
  ota_password: !secret ota_password

packages:
  broccoliboy.gosund-sw5: github://broccoliboy/esphome-config/devices/gosund-sw5.yaml@main
