substitutions:
  log_level: INFO
  log_baud_rate: '115200'
  flash_write_interval: 10min

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

preferences:
  flash_write_interval: ${flash_write_interval}

packages:
  wifi: !include wifi.yaml
  api: !include api.yaml
  ota: !include ota.yaml
  day_night: !include day_night.yaml
  status: !include status.yaml
  restart: !include restart.yaml
  version: !include version.yaml
  time: !include time.yaml
  logger: !include logger.yaml
  uptime: !include uptime.yaml
  web_server: !include web_server.yaml
