substitutions:
  log_level: none
  log_baud_rate: '115200'
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ssid_fallback: !secret wifi_ssid_fallback
  wifi_password_fallback: !secret wifi_password_fallback
  api_key: !secret api_key
  ota_password: !secret ota_password
  flash_write_interval: 10min

${platform}:
  board: ${board}

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  build_path: ./build/${device_name}

preferences:
  flash_write_interval: ${flash_write_interval}

packages:
  wifi: !include ../components/wifi.yaml
  api: !include ../components/api.yaml
  ota: !include ../components/ota.yaml
  day_night: !include ../components/day_night.yaml
  status_sensor: !include ../components/status.yaml       
  restart_button: !include ../components/restart.yaml
  version_sensor: !include ../components/version.yaml
  time: !include ../components/time.yaml
  # logger:           !include ../components/logger.yaml
  # status_sensor:    !include binary_sensor/status.yaml
  # uptime_sensor:    !include sensor/uptime.yaml
  # wifi_sensor:      !include sensor/wifi.yaml
  # wifi_info_sensor: !include text_sensor/wifi_info.yaml
  # time:             !include time/time.yaml
